/* Original bindScene / evidence-to-record flow, adapted to chapter art and layout. */
(()=>{'use strict';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ids=[],queue=[],scheduled=false,popup=null,inspect=()=>{},active=0;
const quiet=()=>DaramEffects.get()!=='standard'||matchMedia('(prefers-reduced-motion: reduce)').matches;
function sync(found,onInspect){ids=found.slice();inspect=onInspect;}
function dismiss(){popup?.remove();popup=null;}
function fly(id,from){const target=document.getElementById('notebook');if(quiet()||!target||!from)return;const a=from.getBoundingClientRect(),b=target.getBoundingClientRect(),f=document.createElement('div');f.className='evidence-to-record';f.innerHTML=DaramEvidenceArt.thumb(id,EVIDENCE[id].title);f.style.left=a.left+a.width/2+'px';f.style.top=a.top+a.height/2+'px';document.body.append(f);DaramAudio.fx('swoosh');const anim=f.animate([{transform:'translate(-50%,-50%) scale(1.4)'},{transform:`translate(${(b.x+b.width/2-a.x-a.width/2)*.5}px,${(b.y+b.height/2-a.y-a.height/2)*.5-60}px) scale(1) rotate(-12deg)`,offset:.5},{transform:`translate(${b.x+b.width/2-a.x-a.width/2}px,${b.y+b.height/2-a.y-a.height/2}px) scale(.35)`}],{duration:620,easing:'cubic-bezier(.5,0,.6,1)',fill:'forwards'});anim.finished.catch(()=>{}).finally(()=>{f.remove();if(target.isConnected)target.animate([{transform:'scale(1)'},{transform:'scale(1.18)'},{transform:'scale(1)'}],{duration:320});});}
function draw(batch){dismiss();active=0;popup=document.createElement('section');popup.id='acquired-item';popup.setAttribute('role','status');popup.setAttribute('aria-live','polite');popup.dataset.motion=quiet()?'simple':'standard';popup.innerHTML=`<small class="acquisition-kicker">${batch.length>1?'증거 '+batch.length+'개 획득!':'증거 획득!'}</small><div class="acquisition-items">${batch.map(id=>`<button data-acquired="${id}" aria-label="${esc(EVIDENCE[id].title)} 획득 설명" aria-pressed="false">${DaramEvidenceArt.thumb(id,EVIDENCE[id].title)}</button>`).join('')}</div><h3></h3><p></p><div class="acquisition-actions"><button id="acquired-store">수첩에 넣기</button><button id="acquired-inspect">자세히 검사</button></div>`;document.getElementById('game').append(popup);const select=i=>{active=i;const e=EVIDENCE[batch[i]];popup.querySelector('h3').textContent=e.title;popup.querySelector('p').textContent=e.desc;popup.querySelectorAll('[data-acquired]').forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));};popup.querySelectorAll('[data-acquired]').forEach((b,i)=>b.onclick=()=>select(i));select(0);document.getElementById('acquired-store').onclick=()=>{const id=batch[active],from=popup.querySelector('[aria-pressed=true] .record-thumb');fly(id,from);dismiss();};document.getElementById('acquired-inspect').onclick=()=>{const id=batch[active];dismiss();inspect(id);};}
function show(id){queue.push(id);if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;const batch=[...new Set(queue)];queue=[];if(batch.length)draw(batch);});}
// A new gameplay action clears the discovery card; it never blocks scene input.
document.addEventListener('click',e=>{if(popup&&e.target.closest('button,a,input,select')&&!e.target.closest('#acquired-item'))dismiss();},true);
window.DaramAcquisition={sync,show,dismiss};
})();
