/* Generated by tools/extract_audio.py from original game.html. */
(()=>{
const S={sound:false};
var AC=null,MASTER,BGMG,SFXG,NOISE,MGAIN=2.4;
function ac(){
  if(!AC){try{
    AC=new (window.AudioContext||window.webkitAudioContext)();
    MASTER=AC.createGain();MASTER.gain.value=S.sound?MGAIN:0;
    try{var CMP=AC.createDynamicsCompressor();CMP.threshold.value=-16;CMP.knee.value=10;CMP.ratio.value=5;CMP.attack.value=.004;CMP.release.value=.22;MASTER.connect(CMP);CMP.connect(AC.destination);window.__CMP=CMP}catch(e){MASTER.connect(AC.destination)}
    BGMG=AC.createGain();BGMG.gain.value=.1;BGMG.connect(MASTER);
    SFXG=AC.createGain();SFXG.gain.value=.42;SFXG.connect(MASTER);
    var len=AC.sampleRate*.5;NOISE=AC.createBuffer(1,len,AC.sampleRate);var d=NOISE.getChannelData(0);for(var i=0;i<len;i++)d[i]=Math.random()*2-1;
  }catch(e){AC=null}}
  if(AC&&AC.state==="suspended"){try{AC.resume()}catch(e){}}
  return AC;
}
function tone(f,dur,type,vol,when,dest,to){
  var a=ac();if(!a||!S.sound)return;var t=a.currentTime+(when||0);
  var o=a.createOscillator(),g=a.createGain();o.type=type||"sine";o.frequency.setValueAtTime(f,t);
  if(to)o.frequency.exponentialRampToValueAtTime(to,t+dur);
  g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol||.3,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  o.connect(g);g.connect(dest||SFXG);o.start(t);o.stop(t+dur+.03);
}
function noise(dur,vol,when,freq,type,dest,sweepTo){
  var a=ac();if(!a||!S.sound)return;var t=a.currentTime+(when||0);
  var s=a.createBufferSource();s.buffer=NOISE;var f=a.createBiquadFilter();f.type=type||"lowpass";f.frequency.setValueAtTime(freq||1200,t);
  if(sweepTo)f.frequency.exponentialRampToValueAtTime(sweepTo,t+dur);
  var g=a.createGain();g.gain.setValueAtTime(vol||.3,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  s.connect(f);f.connect(g);g.connect(dest||SFXG);s.start(t);s.stop(t+dur+.02);
}
function kick(w,v,dest){tone(150,.2,"sine",v||.9,w,dest,42)}
function snare(w,v,dest){noise(.13,v||.5,w,1800,"highpass",dest);tone(200,.08,"triangle",(v||.5)*.5,w,dest,140)}
function hat(w,v,dest){noise(.035,v||.18,w,7000,"highpass",dest)}
var SFX={
  tap:function(){tone(700,.06,"square",.08)},
  type:function(){tone(1250,.025,"triangle",.05)},
  found:function(){[523,659,784,1047].forEach(function(f,i){tone(f,.28,"triangle",.3,i*.08)});noise(.2,.08,0,5000)},
  wrong:function(){tone(220,.4,"sawtooth",.16,0,null,100)},
  steps:function(){noise(.07,.35,0,500);noise(.07,.3,.22,450);noise(.07,.25,.44,500)},
  gotcha:function(){try{navigator.vibrate&&navigator.vibrate([90,50,140])}catch(e){}SFX.slam()},
  slam:function(){tone(110,.28,"sine",1,0,null,38);noise(.22,.9,0,420);noise(.08,.4,0,2400,"highpass")},
  shout:function(){[311,392,466,622].forEach(function(f){tone(f,.32,"sawtooth",.13,.02);tone(f*1.005,.32,"square",.07,.02)});noise(.25,.35,0,3000,"bandpass",null,800)},
  buzz:function(){tone(146,.45,"sawtooth",.22,0,null,90);tone(155,.45,"square",.12,0,null,95)},
  swoosh:function(){noise(.35,.45,0,300,"bandpass",null,4000)},
  blip:function(f){if(!f)return;tone(f,.035,"square",.045)},
  lock:function(){tone(220,.08,"square",.3);noise(.12,.6,0,1800,"highpass");tone(160,.2,"square",.25,.08,null,120)},
  unlock:function(){noise(.25,.5,0,5000,"highpass");[1319,1760,2093].forEach(function(f,i){tone(f,.2,"triangle",.2,i*.06)})},
  select:function(){tone(880,.05,"square",.1);tone(1320,.07,"square",.08,.05)},
  shock:function(){tone(700,.35,"square",.16,0,null,160);noise(.12,.4,0,3000,"highpass")},
  blush:function(){[660,880,1100].forEach(function(f,i){tone(f,.14,"sine",.2,i*.07)})},
  huh:function(){tone(420,.12,"triangle",.3);tone(620,.2,"triangle",.3,.12,null,760)},
  cry:function(){[0,.25].forEach(function(w){tone(560,.22,"sine",.2,w,null,380)})},
  thinkin:function(){tone(1568,.5,"sine",.08);tone(2093,.6,"sine",.06,.08)},
  knock:function(){tone(180,.07,"triangle",.7,0,null,120);noise(.05,.5,0,1500);tone(180,.07,"triangle",.7,.16,null,120);noise(.05,.5,.16,1500)},
  gulp:function(){tone(300,.12,"sine",.5,0,null,520);tone(240,.1,"sine",.35,.13,null,160)},
  laugh:function(){[0,.13,.26].forEach(function(w,i){tone(520-i*40,.1,"square",.12,w,null,420-i*40)})},
  crash:function(){noise(.9,.9,0,2400,"lowpass",null,200);tone(90,.8,"sine",.9,0,null,30);[1760,1320,990,740].forEach(function(f,i){tone(f,.18,"triangle",.2,.1+i*.08)})},
  heart:function(){tone(70,.14,"sine",1,0,null,45);tone(64,.16,"sine",.8,.2,null,40)},
  gavel:function(){[0,.32,.64].forEach(function(w){tone(620,.09,"triangle",.5,w,null,380);noise(.06,.6,w,2600,"highpass");tone(120,.15,"sine",.6,w,null,60)})},
  present:function(){[1568,2093,2637].forEach(function(f,i){tone(f,.25,"triangle",.22,i*.05)})},
  life:function(){tone(440,.25,"square",.14,0,null,220);tone(330,.35,"square",.12,.18,null,160)},
  stamp:function(){noise(.2,.8,0,260);tone(95,.35,"sine",.7,0,null,45)},
  roll:function(){for(var i=0;i<18;i++)noise(.05,.18+i*.012,i*.06,1600)},
  ok:function(){tone(784,.15,"triangle",.3);tone(1175,.3,"triangle",.3,.1)},
  ng:function(){tone(300,.3,"square",.12,0,null,200)},
  win:function(){var m=[[523,.12],[523,.12],[523,.12],[523,.36],[415,.36],[466,.36],[523,.24],[466,.12],[523,.9]],t=0;m.forEach(function(x){tone(x[0],x[1]+.05,"square",.13,t);tone(x[0]/2,x[1]+.05,"triangle",.2,t);t+=x[1]});kick(0,.6);kick(1.08,.6);snare(1.08+.36,.4);[262,330,392].forEach(function(f){tone(f,1.4,"triangle",.14,t-.9)})},
  page:function(){noise(.12,.12,0,2600)},
  hush:function(){tone(70,1.1,"sine",.7,0,null,48);tone(140,1,"triangle",.12,.05,null,90);noise(.8,.08,0,260)},
  door:function(){tone(988,.35,"sine",.25);tone(784,.5,"sine",.25,.22)},
  hold:function(){try{navigator.vibrate&&navigator.vibrate(60)}catch(e){}noise(.14,.6,0,500,"bandpass",null,3200);tone(130,.28,"sine",1,0,null,42);noise(.1,.7,.02,300);[392,523,659].forEach(function(f){tone(f,.24,"sawtooth",.1,.03);tone(f*1.006,.24,"square",.05,.03)})},
  cutin:function(){noise(.3,.45,0,300,"bandpass",null,4200);tone(98,.32,"sine",1,.14,null,38);noise(.16,.75,.14,480);[262,330,392,523].forEach(function(f,i){tone(f,.3,"square",.08,.16+i*.05);tone(f/2,.3,"triangle",.14,.16+i*.05)})}
};
var PAT={
  calm:{bpm:104,lead:"triangle",lv:.55,mel:[72,null,76,79,null,76,72,null,74,null,77,81,null,77,74,null,72,null,76,79,null,84,83,81,79,null,77,null,76,null,null,null],bass:[48,48,45,45,41,41,43,43],dr:"k...s...k.k.s...",dv:.35},
  sneak:{bpm:92,lead:"triangle",lv:.5,mel:[69,null,72,null,76,null,74,72,69,null,67,null,69,null,null,null,69,null,72,null,76,null,79,77,76,null,74,null,72,null,null,null],bass:[45,45,43,43,41,41,40,40],dr:"..h...h...h...h.",dv:.3},
  talk:{bpm:116,lead:"square",lv:.28,mel:[69,null,72,74,76,null,74,72,71,null,72,71,69,null,null,null,69,null,72,74,76,null,79,77,76,null,74,72,71,null,null,null],bass:[45,45,41,41,43,43,40,40],dr:"k.h.s.h.k.hks.h.",dv:.4},
  battle:{bpm:138,lead:"square",lv:.3,mel:[64,null,64,67,null,64,71,null,69,null,67,null,64,null,62,null,64,null,64,67,null,71,72,null,71,null,69,null,67,null,null,null],bass:[40,40,40,40,43,43,38,38],dr:"k.s.kks.k.s.kkss",dv:.55,hats:true},
  pursuit:{bpm:160,lead:"sawtooth",lv:.22,mel:[76,null,76,79,78,null,76,74,76,null,83,null,81,79,78,76,76,null,76,79,78,null,76,74,71,null,74,76,null,null,null,null],bass8:[40,40,52,40,40,52,40,52,43,43,55,43,38,38,50,38],dr:"k.s.k.s.k.s.kkss",dv:.6,hats:true},
  win:{bpm:96,lead:"triangle",lv:.5,mel:[72,null,79,null,77,76,74,null,72,null,76,null,79,null,null,null,77,null,76,74,72,null,74,76,72,null,null,null,null,null,null,null],bass:[48,48,43,43,45,45,41,43],dr:"k...s...k...s.s.",dv:.3}
};
var BGM={mode:null,timer:null,next:0,step:0};
function mf(n){return 440*Math.pow(2,(n-69)/12)}
function bgm(mode){
  if(BGM.mode===mode&&BGM.timer)return;
  if(BGM.timer){clearInterval(BGM.timer);BGM.timer=null}
  BGM.mode=mode;
  if(!mode||!S.sound)return;
  var a=ac();if(!a)return;
  var p=PAT[mode],sd=60/p.bpm/2;BGM.next=a.currentTime+.15;BGM.step=0;
  BGM.timer=setInterval(function(){
    while(BGM.next<a.currentTime+.35){
      var st=BGM.step,w=BGM.next-a.currentTime,n=p.mel[st%p.mel.length];
      if(n){tone(mf(n),sd*1.7,p.lead,p.lv,w,BGMG);if(p.lead!=="triangle")tone(mf(n-12),sd*1.7,"triangle",p.lv*.6,w,BGMG)}
      if(p.bass8)tone(mf(p.bass8[st%p.bass8.length]),sd*.9,"triangle",.9,w,BGMG);
      else if(st%4===0)tone(mf(p.bass[Math.floor(st/4)%p.bass.length]),sd*3.6,"sine",.85,w,BGMG);
      var d=p.dr[st%p.dr.length],v=p.dv;
      if(d==="k")kick(w,v*1.6,BGMG);else if(d==="s")snare(w,v,BGMG);else if(d==="h")hat(w,v*.7,BGMG);
      if(p.hats&&d!=="h")hat(w,v*.35,BGMG);
      BGM.next+=sd;BGM.step++;
    }
  },90);
}

const PREF='daram-chapter-one-audio-v1';
let prefs={music:.55,effects:.7},unlocked=false,wanted='calm',lastBlip=0;
try{const p=JSON.parse(localStorage.getItem(PREF));for(const k of ['music','effects'])if(Number.isFinite(p?.[k]))prefs[k]=Math.max(0,Math.min(1,p[k]));}catch{}
function levels(){if(!AC)return;BGMG.gain.value=.1*prefs.music;SFXG.gain.value=.42*prefs.effects;MASTER.gain.value=S.sound?MGAIN:0;}
function pause(){S.sound=false;bgm(null);levels();if(AC&&AC.state==='running')AC.suspend().catch(()=>{});}
function resume(){if(!unlocked||document.hidden||!(prefs.music||prefs.effects))return pause();S.sound=true;try{const a=ac();if(a?.state==='suspended')a.resume().catch(()=>{});levels();if(prefs.music)bgm(wanted);else bgm(null);}catch{}}
window.DaramAudio={
 unlock(){unlocked=true;resume();},
 music(mode){if(!PAT[mode])return;wanted=mode;if(unlocked&&!document.hidden)resume();},
 fx(name,...args){if(!unlocked||!S.sound||document.hidden||!prefs.effects)return;if(name==='blip'){const now=Date.now();if(now-lastBlip<65)return;lastBlip=now;}try{SFX[name]?.(...args);}catch{}},
 set(key,value){if(!['music','effects'].includes(key)||!Number.isFinite(value))return;prefs[key]=Math.max(0,Math.min(1,value));try{localStorage.setItem(PREF,JSON.stringify(prefs));}catch{}resume();},
 get(){return {...prefs};},
 status(){return {unlocked,mode:wanted,playing:!!BGM.timer,context:AC?.state||'uninitialized',musicGain:BGMG?.gain.value||0,effectsGain:SFXG?.gain.value||0};}
};
document.addEventListener('visibilitychange',()=>document.hidden?pause():resume());
window.addEventListener('pagehide',pause);window.addEventListener('pageshow',()=>{if(unlocked)resume();});
// Start or resume only from an explicit game interaction, including iOS touch-generated clicks.
document.addEventListener('click',e=>{if(e.target.closest('#game button,#game select,#game input'))window.DaramAudio.unlock();},true);

})();
