const{chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8070/chapter-one/');await p.locator('#start').click();assert.equal(await p.evaluate(()=>DaramArt.has('daram')),true);
await p.evaluate(()=>{let k='daram-illustrated-chapter1-v1',s=JSON.parse(localStorage.getItem(k));s.mode='questions';s.speed=0;s.asked=['delivery'];localStorage.setItem(k,JSON.stringify(s))});await p.reload();await p.locator('#continue').click();assert.equal(await p.locator('#actor').getAttribute('data-art'),'pixel');await p.screenshot({path:__dirname+'/previews/indie-dialogue.png'});
await p.locator('#nav-scene').tap();await p.waitForFunction(()=>document.getElementById('world').dataset.ready==='true');assert.equal(await p.locator('#actor').isHidden(),true);assert.equal(await p.locator('.scene-selection').count(),0);await p.locator('[data-spot=receipt]').tap();await p.waitForTimeout(800);assert.equal(await p.locator('.sheet').count(),0);assert.match(await p.locator('.scene-selection').innerText(),/접수증/);assert.match(await p.locator('.scene-clue-card h3').innerText(),/접수증/);assert.equal(await p.locator('[data-spot=receipt]').getAttribute('aria-pressed'),'true');await p.screenshot({path:__dirname+'/previews/indie-investigation.png'});
await p.locator('#inspect-selected').tap();await p.locator('#return').tap();await p.waitForTimeout(1200);assert.equal(await p.locator('.scene-selection').isVisible(),true);await p.locator('[data-spot=tray]').tap();assert.equal(await p.locator('.scene-selection').count(),1);assert.equal(await p.locator('[data-spot=receipt]').getAttribute('aria-pressed'),'false');assert.match(await p.locator('.scene-selection').innerText(),/받침/);
await p.locator('#notebook').tap();assert.equal(await p.locator('.evidence-grid .pixel-evidence').count(),2);await p.screenshot({path:__dirname+'/previews/indie-evidence.png'});await p.locator('[data-close]').tap();await p.locator('#nav-fight').tap();await p.locator('#present').tap();assert.match(await p.locator('.comparison-claim').innerText(),/까로의 증언/);await p.locator('[data-evidence=receipt]').tap();await p.screenshot({path:__dirname+'/previews/indie-comparison.png'});await p.locator('#record-open').tap();assert.match(await p.locator('.comparison-claim').innerText(),/까로/);assert.match(await p.locator('#submit').innerText(),/접수증/);assert.deepEqual(errors,[]);await p.close();
const f=await b.newPage();await f.route('**/assets/*-pixel.png',r=>r.abort());await f.goto('http://127.0.0.1:8070/chapter-one/');await f.locator('#retry-load').waitFor({state:'visible'});assert.equal(await f.locator('#start').isDisabled(),true);await f.close();console.log('PASS persistent selected object/card, close/reselect, no investigation portrait, pixel icons/characters, testimony comparison, critical title art failure recovery.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
