const{chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const base=process.env.CHAPTER_URL||'http://127.0.0.1:8070/chapter-one/',KEY='daram-illustrated-chapter1-v1';
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),errors=[];
const state=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
async function open(size){const p=await b.newPage({viewport:size});p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator('#start').click();await p.locator('#settings').click();await p.locator('#speed').selectOption('0');await p.locator('[data-close]').click();return p;}
async function step(p){await p.waitForTimeout(180);await p.locator('#advance').click();}
async function read(p){for(let i=0;i<90&&await p.locator('#advance').count();i++)await step(p);if(await p.locator('#advance').count()){console.log('READ STALLED',await p.evaluate(k=>({state:JSON.parse(localStorage.getItem(k)),modal:document.getElementById('modal').innerHTML.slice(0,100),title:document.getElementById('title').hidden}),KEY));}assert.equal(await p.locator('#advance').count(),0);}
async function detail(p,id,inspect=false){await p.locator('#notebook').click();await p.locator('[data-tab=evidence]').click();await p.locator(`[data-evidence="${id}"]`).click();if(inspect&&await p.locator('#examine').count())await p.locator('#examine').click();await p.locator('#return').click();}
async function present(p,id){await p.locator('#present').click();await p.locator(`[data-evidence="${id}"]`).click();assert.equal(await p.locator('[data-record="'+id+'"]').getAttribute('aria-pressed'),'true');assert.ok((await p.locator('#submit').innerText()).includes(await p.locator('#selected-record-name').innerText()));assert.match(await p.locator('.current-claim').innerText(),/문장/);await p.locator('#submit').click();await p.waitForFunction(k=>['dialogue','retry'].includes(JSON.parse(localStorage.getItem(k)).mode),KEY);}
async function combine(p,a,c){await p.locator('#notebook').click();await p.locator('#combine').click();await p.locator(`[data-combine="${a}"]`).click();await p.locator(`[data-combine="${c}"]`).click();await p.locator('#combine-go').click();}
async function sceneReady(p){await p.waitForFunction(()=>document.getElementById('world').dataset.ready==='true');}
try{
 const p=await open({width:390,height:844});await step(p);await step(p);assert.equal(await p.locator('#actor').getAttribute('data-actor'),'daram');assert.match(await p.locator('.nameplate').innerText(),/아빠/);assert.doesNotMatch(await p.locator('.nameplate').innerText(),/곁에서|옆에서/);await p.screenshot({path:path.join(__dirname,'previews/v2-dad-reaction.png')});await read(p);
 await p.locator('[data-q=delivery]').click();await read(p);await p.locator('[data-q=spoon]').click();await step(p);await step(p);assert.equal(await p.locator('#actor').getAttribute('data-emotion'),'3');await read(p);
 await p.locator('#notebook').click();await p.locator('[data-tab=people]').click();assert.match(await p.locator('.person-note').filter({hasText:'까로'}).innerText(),/못생김/);await p.screenshot({path:path.join(__dirname,'previews/v2-people.png')});await p.locator('[data-close]').click();
 await p.locator('#settings').click();await p.locator('#save-menu').click();await p.locator('[data-save="0"]').click();await p.locator('[data-close]').click();
 await p.locator('#nav-scene').click();await sceneReady(p);const range=await p.locator('#panorama').evaluate(e=>e.scrollWidth-e.clientWidth);assert.ok(range>200);assert.equal(await p.locator('.spot').evaluateAll(a=>a.every(e=>!e.textContent&&getComputedStyle(e).backgroundColor==='rgba(0, 0, 0, 0)')),true);
 await p.locator('#pan-left').click();await p.waitForTimeout(600);assert.ok(await p.locator('#panorama').evaluate(e=>e.scrollLeft)<5);await p.screenshot({path:path.join(__dirname,'previews/v2-investigation-left.png')});
 // A drag across the scene must pan without collecting a clue.
 const before=(await state(p)).found.length;await p.mouse.move(310,360);await p.mouse.down();await p.mouse.move(90,360,{steps:12});await p.mouse.up();assert.ok(await p.locator('#panorama').evaluate(e=>e.scrollLeft)>100);assert.equal((await state(p)).found.length,before);
 for(const id of ['receipt','tray','clock','cabinet']){await p.locator(`[data-spot=${id}]`).click();assert.ok(await p.locator('.scene-selection').isVisible());await p.locator(`.evidence-art[data-art=${id}]`).waitFor();assert.ok(await p.locator('.evidence-art img').evaluate(e=>e.complete&&e.naturalWidth>0));if(id==='receipt'){assert.equal((await state(p)).system.exam.receipt,undefined);await p.screenshot({path:path.join(__dirname,'previews/v2-evidence.png')});}await p.locator('#return').click();}
 await p.locator('#notebook').click();await p.locator('[data-tab=evidence]').click();await p.locator('[data-evidence=receipt]').click();assert.match(await p.locator('#selected-record-name').innerText(),/접수증/);await p.locator('[data-record=tray]').click();assert.match(await p.locator('#selected-record-name').innerText(),/받침/);await p.locator('#detail-back').click();assert.equal(await p.locator('[data-evidence=tray]').getAttribute('aria-pressed'),'true');await p.locator('[data-close]').click();await p.locator('#pan-right').click();await p.waitForTimeout(500);await p.screenshot({path:path.join(__dirname,'previews/v2-investigation-right.png')});
 await p.locator('#nav-fight').click();await p.locator('#next').click();await present(p,'receipt');await read(p);assert.equal((await state(p)).system.hp,5);assert.equal((await state(p)).round,1); // reading alone does not inspect
 await detail(p,'receipt',true);await combine(p,'receipt','t_paid');assert.match(await p.locator('#sheet-title').innerText(),/서명이 확인/);await p.locator('#return').click();
 await p.locator('#prev').click();await present(p,'receipt');await read(p);assert.equal((await state(p)).system.hp,4);await p.locator('#next').click();await present(p,'tray');await read(p);assert.equal((await state(p)).system.hp,3);
 await p.reload();await p.locator('#continue').click();assert.equal((await state(p)).system.hp,3);await present(p,'cx_reception_0');await read(p);assert.equal((await state(p)).round,2);
 await p.locator('[data-q=key]').click();await read(p);await detail(p,'key',true);await combine(p,'key','cabinet');await p.locator('#return').click();await p.locator('#nav-fight').click();await p.locator('#next').click();await present(p,'cx_reception_1');await read(p);assert.equal((await state(p)).mode,'review');assert.ok((await state(p)).system.unlocked.includes('door:archive'));
 await p.locator('#deduce').click();assert.equal((await state(p)).mode,'review');await combine(p,'roster','report');assert.match(await p.locator('#combine-feedback').innerText(),/검사/);await p.locator('[data-close]').click();
 await detail(p,'roster',true);await detail(p,'report',true);await combine(p,'roster','report');await p.screenshot({path:path.join(__dirname,'previews/v2-combination.png')});await p.locator('#return').click();await p.locator('#deduce').click();
 for(const [i,val] of ['karo','window','steal'].entries())await p.locator(`[data-answer="${i}"]`).selectOption(val);await p.locator('#finish-case').click();assert.match(await p.locator('#answer-feedback').innerText(),/다른 칸/);
 for(const [i,val] of ['mungchi','cabinet','hold'].entries())await p.locator(`[data-answer="${i}"]`).selectOption(val);await p.locator('#finish-case').click();await read(p);assert.equal((await state(p)).finished,true);assert.equal((await state(p)).system.result.solved,true);await p.screenshot({path:path.join(__dirname,'previews/v2-ending.png')});
 await p.locator('#settings').click();await p.locator('#save-menu').click();await p.locator('[data-load="0"]').click();await p.locator('#load-confirm').click();assert.equal((await state(p)).mode,'questions');assert.equal((await state(p)).round,1);
 for(let i=0;i<3;i++){await p.locator('#nav-hint').click();await p.locator('#use-hint').click();await p.locator('[data-close]').click();}await p.locator('#nav-hint').click();assert.equal(await p.locator('#use-hint').count(),0);assert.equal((await state(p)).system.hints,3);await p.locator('[data-close]').click();await p.close();
 console.log('PASS: full chapter, no visible hotspots, drag, evidence inspection, original battle/HP, 3 combinations including testimony, locations, final deduction, slots, hints, save migration.');
 for(const size of [{width:360,height:640},{width:390,height:844},{width:430,height:932},{width:844,height:390},{width:1280,height:720}]){
  const p=await open(size);await step(p);await p.screenshot({path:path.join(__dirname,`previews/v2-layout-${size.width}.png`)});await read(p);const actor=await p.locator('#actor').boundingBox(),panel=await p.locator('#panel').boundingBox();assert.ok(Number(await p.locator('#actor').getAttribute('data-face-width'))<=await p.locator('#game').evaluate(e=>e.clientWidth)*.4);if(actor.x+actor.width>panel.x)assert.ok(Number(await p.locator('#actor').getAttribute('data-eye-y'))+Number(await p.locator('#actor').getAttribute('data-face-width'))*.55<panel.y,'crow face visible');if(size.height>size.width){assert.ok(Number(await p.locator('#actor').getAttribute('data-crop-end'))<=panel.y+panel.height-2,'crow cropped edge stays behind dialogue window');assert.ok(Number(await p.locator('#actor').getAttribute('data-crop-end'))>panel.y,'crow portrait meets dialogue window');}await p.screenshot({path:path.join(__dirname,`previews/soft-questions-${size.width}.png`)});
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#nav-scene').click();await sceneReady(p);for(const side of ['left','right']){const button=p.locator('#pan-'+side);if(await button.isEnabled())await button.click();await p.waitForTimeout(500);}assert.equal(await p.locator('.spot').evaluateAll(a=>a.every(e=>e.children.length===0)),true);
  await p.locator('[data-spot=receipt]').click();await p.locator('.sheet').waitFor();const sheet=await p.locator('.sheet').boundingBox();assert.ok(sheet.y>=0&&sheet.y+sheet.height<=size.height+1);await p.locator('#examine').click();await p.locator('#return').click();await p.close();console.log(`PASS ${size.width}×${size.height} layout and scene interaction`);
 }
 assert.deepEqual(errors,[]);console.log('No browser errors.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
