(()=>{'use strict';
const $=id=>document.getElementById(id), KEY='daram-illustrated-chapter1-v1';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:1,mode:'dialogue',lines:STORY.intro,index:0,after:'questions',round:1,found:[],read:[],asked:[],pressed:[],statement:0,log:[],speed:28,finished:false,moods:{}});
let s=fresh(),timer=null,full='',typed=0,last=0,returnFocus=null,toastTimer;
let checkpoint=null;try{let v=JSON.parse(localStorage.getItem(KEY));if(v?.version===1&&Array.isArray(v.lines)&&Array.isArray(v.found)&&Array.isArray(v.log))checkpoint={...fresh(),...v};}catch{}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s));}catch{}};
function tell(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2200);}
function stop(){clearInterval(timer);timer=null;$('panel').classList.remove('typing');}
function actor(id,mood=0){const a=$('actor');a.hidden=!id;a.dataset.actor=id||'';a.style.setProperty('--expression',Math.max(0,Math.min(2,mood)));if(id)a.style.backgroundImage=`url(${window.ART?.[id]||'assets/'+id+'.png'})`;}
function add(id){if(!s.found.includes(id)){s.found.push(id);save();}count();}
function count(){$('count').textContent=s.found.length?' '+s.found.length:'';}
function dialogue(lines,after,actorId=s.round===1?'karo':'mungchi'){s.mode='dialogue';s.lines=lines.map(l=>({...l,actor:Object.prototype.hasOwnProperty.call(l,'actor')?l.actor:actorId}));s.index=0;s.after=after;save();render();}
function speak(){const l=s.lines[s.index];if(!l){arrive(s.after);return;}const who=Object.prototype.hasOwnProperty.call(l,'actor')?l.actor:'karo';if(who&&l.who===who)s.moods[who]=l.mood;actor(who,who?s.moods[who]||0:0);$('chaptermark').hidden=!l.establish;$('chaptermark').innerHTML='<small>첫 번째 사건</small><h2>사라진 봉투</h2><p>눈길 거처 · 어느 겨울 오후</p>';
 const name=l.thought?'다람':NAMES[l.who];$('panel').className='dialogue';$('panel').innerHTML=`<div class="nameplate">${escape(name)}<small>${l.thought?'속마음':l.who==='narr'?'':l.who==='dad'?'곁에서':'대화 중'}</small></div><p id="text" class="${l.thought?'thought':l.who==='narr'?'narration':''}" aria-live="off"></p><button id="advance" aria-label="대사 읽기 · 다음"><span>⌄</span></button>`;
 const id=s.lines.map(x=>x.text).join('|')+'#'+s.index;if(s.logged!==id){s.log.push({name,text:l.text,thought:!!l.thought});s.logged=id;save();}
 full=l.text;typed=0;$('advance').onclick=advance;
 if(!s.speed){$('text').textContent=full;typed=full.length;}else{$('panel').classList.add('typing');timer=setInterval(()=>{if($('modal').childElementCount)return;typed++;$('text').textContent=full.slice(0,typed);if(typed>=full.length)stop();},s.speed);}
}
function advance(){if(s.mode!=='dialogue'||$('modal').childElementCount||!$('title').hidden)return;const now=Date.now();if(now-last<170)return;last=now;if(timer){stop();typed=full.length;$('text').textContent=full;return;}s.index++;save();render();}
function arrive(mode){s.mode=mode;if(mode==='second'){s.round=2;s.mode='questions';s.statement=0;}if(mode==='review'){['envelope','roster','report'].forEach(add);s.mode='review';}save();render();}
function render(){stop();count();$('chaptermark').hidden=true;$('objective').hidden=true;$('hotspots').innerHTML='';$('panel').className='';
 if(s.mode==='dialogue')speak();else if(s.mode==='questions')questions();else if(s.mode==='investigate')investigate();else if(s.mode==='testimony')testimony();else if(s.mode==='review')review();else if(s.mode==='done')ending();
}
const button=(id,t,cls='')=>`<button id="${id}" class="${cls}">${t}</button>`;
function questions(){actor(s.round===1?'karo':'mungchi',0);$('panel').className='interactive';
 const qs=s.round===1?Object.entries(STORY.questions).map(([id,q])=>`<button data-q="${id}">${q.title}<small>${s.asked.includes(id)?'다시 듣기':'›'}</small></button>`).join(''):`<button data-q="key">목에 건 열쇠는 어디에 쓰나요?<small>${s.found.includes('key')?'다시 듣기':'›'}</small></button><button data-q="reason">봉투가 없어진 걸 언제 알았나요?<small>›</small></button>`;
 $('panel').innerHTML=`<div class="nameplate">${s.round===1?'까로':'뭉치'}<small>${s.round===1?'배달부':'접수 담당자'}</small></div><div class="questions">${qs}</div><div class="actions">${button('investigate','현장 조사')}${button('verify','증언 확인','gold')}</div>`;
 $('panel').querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{if(s.mode!=='questions')return;let id=b.dataset.q;if(!s.asked.includes(id))s.asked.push(id);if(id==='key'){add('key');dialogue(STORY.keyFound,'questions');}else if(id==='reason')dialogue([line('daram','봉투가 없어진 건 언제 알았어요?'),line('mungchi','주민 한 분이 돈을 받으러 왔을 때요.',1),line('daram','그 전에 받침을 확인했나요?'),line('mungchi','…계속 보고 있지는 않았어요.',1)],'questions');else dialogue(STORY.questions[id].lines,'questions');});
 $('investigate').onclick=()=>{s.mode='investigate';save();render();};$('verify').onclick=()=>{if(s.round===1&&!s.asked.includes('delivery')){tell('먼저 봉투를 누구에게 줬는지 물어보자.');return;}s.mode='testimony';s.statement=0;save();render();};}
// Hotspots use the actual source image coordinates, recalculated after resize.
const spots=[{id:'receipt',x:.16,y:.472},{id:'tray',x:.47,y:.53},{id:'clock',x:.623,y:.26},{id:'cabinet',x:.885,y:.289}];
function placeSpots(){const w=$('scene').clientWidth,h=$('scene').clientHeight,land=matchMedia('(orientation:landscape) and (max-height:550px)').matches,scale=land?Math.min(w/941,h/1672):Math.max(w/941,h/1672),dw=941*scale,dh=1672*scale;document.querySelectorAll('[data-spot]').forEach(b=>{const p=spots.find(p=>p.id===b.dataset.spot);b.style.left=Math.max(48,Math.min(w-48,p.x*dw+(w-dw)/2))+'px';b.style.top=Math.max(88,p.y*dh+(h-dh)*.5)+'px';});}
function investigate(){actor(null);$('panel').className='investigation';
 // Keep game copy Korean, including every interactive state.
 $('panel').innerHTML=`<div class="nameplate">현장 조사</div><p>서류와 물건을 직접 살펴보자.</p><div class="actions">${button('back',s.round===1?'까로에게 돌아가기':'뭉치에게 돌아가기')}${button('openbook','수첩')}</div>`;
 $('hotspots').innerHTML=spots.map(p=>`<button class="spot ${s.found.includes(p.id)?'visited':''}" data-spot="${p.id}" aria-label="${EVIDENCE[p.id].title} 조사"><span>⌕</span><small>${EVIDENCE[p.id].title}</small></button>`).join('');placeSpots();document.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>{add(b.dataset.spot);detail(b.dataset.spot,false);});$('back').onclick=()=>{s.mode='questions';save();render();};$('openbook').onclick=()=>inventory(false);}
function claims(){return s.round===1?['오후 세 시에 뭉치에게 봉투를 건넸습니다.','서명을 받았으니 주민 지급도 끝났습니다.']:['봉투는 제가 받아서 접수대에 뒀어요.','주인님 열쇠가 없으니 보관함은 아무도 못 열어요.'];}
function testimony(){actor(s.round===1?'karo':'mungchi',s.round===1?0:1);$('panel').className='interactive testimony';$('panel').innerHTML=`<div class="nameplate">${s.round===1?'까로':'뭉치'}<small>증언</small></div><div class="testimony-head"><span>${s.round===1?'배달이 끝난 뒤':'잠긴 보관함'}</span><span>${s.statement+1} / 2</span></div><p class="claim">${escape(claims()[s.statement])}</p><div class="actions">${button('prev','‹')}${button('press','추궁')}${button('present','증거 제시','gold')}${button('next','›')}</div><button class="text-button" id="back">질문·조사로 돌아가기</button>`;
 $('prev').onclick=$('next').onclick=()=>{s.statement=1-s.statement;save();render();};$('back').onclick=()=>{s.mode='questions';save();render();};$('present').onclick=()=>inventory(true);
 $('press').onclick=()=>{const k=s.round+':'+s.statement;if(!s.pressed.includes(k))s.pressed.push(k);const lines=s.round===1?(s.statement===0?[line('daram','직접 건넨 게 맞나요?'),line('karo','네. 제 앞에서 이름을 썼어요.',1)]:[line('daram','그 서명이 무엇을 확인한다는 뜻이죠?'),line('karo','주민들이 돈을 받았다는 확인이죠.',1),line('daram','서류에 그렇게 적혀 있나요?'),line('karo','확인서니까… 그런 뜻 아닙니까?',2)]):(s.statement===0?[line('daram','받침에 둔 뒤에는요?'),line('mungchi','다른 일을 했어요. 계속 보고 있지는 않았어요.',1)]:[line('daram','보관함을 여는 방법은 그 열쇠 하나뿐인가요?'),line('mungchi','주인님 열쇠는 지금 여기에 없어요.',1),line('daram','그건 대답이 아니에요. 다른 열쇠는요?')]);dialogue(lines,'testimony');};}
function submit(id){close();const correct=s.round===1?'receipt':'key';if(id!==correct){dialogue([line('daram',`(${id==='tray'?'받침이 비었다고 누가 옮겼는지 알 수는 없어.':id==='clock'?'시각만으로 이 말을 반박할 수는 없어.':'이 자료가 지금 문장과 어떻게 어긋나는지 다시 보자.'})`,1,{thought:true})],'testimony');return;}if(s.statement!==1){dialogue([line('daram','(이 자료는 받은 사람을 의심할 이유가 되지 않아. 다른 문장을 확인하자.)',1,{thought:true})],'testimony');return;}if(!s.read.includes(id)){dialogue([line('daram','(제목만 보지 말고, 안에 적힌 내용까지 확인하자.)',1,{thought:true})],'testimony');return;}dialogue(s.round===1?STORY.crowSolved:STORY.keySolved,s.round===1?'second':'review');}
function review(){actor('daram',1);$('panel').className='interactive';$('panel').innerHTML=`<div class="nameplate">다람 <small>두 문서의 차이</small></div><p>엄마의 서명이 확인한 것은 무엇일까?</p><div class="actions">${button('roster','지급 명단 읽기')}${button('report','점검 보고서 읽기')}</div><div class="questions finalchoices"><button data-answer="wrong">명단에 있는 모든 주민의 지급 자격</button><button data-answer="right">건물과 난방, 대피로의 안전 상태</button><button data-answer="wrong">봉투를 실제로 받은 사람</button></div>`;
 $('roster').onclick=()=>detail('roster');$('report').onclick=()=>detail('report');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(!s.read.includes('report')||!s.read.includes('roster')){tell('두 문서의 확인 범위를 먼저 읽어 보자.');return;}if(b.dataset.answer!=='right'){dialogue([line('daram','(보고서의 「점검 범위」와 명단 아래 문구를 다시 비교해 보자.)',1,{actor:'daram',thought:true})],'review');return;}dialogue(STORY.ending,'done','daram');});}
function ending(){s.finished=true;save();actor('daram',0);$('panel').className='interactive ending';$('panel').innerHTML=`<div class="nameplate">첫 번째 사건 · 끝</div><small class="eyebrow">사라진 봉투</small><h2>답을 찾으면,<br>다음 질문이 보인다.</h2><p>봉투는 돌아왔다. 명단에 쓰인 엄마의 이름은<br>아직 풀리지 않은 질문으로 남았다.</p><div class="actions">${button('endingbook','사건 수첩')}${button('replay','처음부터')}</div>`;$('endingbook').onclick=()=>inventory(false);$('replay').onclick=resetPrompt;}
function open(html){returnFocus=document.activeElement;$('modal').innerHTML=`<div class="veil"><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title">${html}</section></div>`;[...$('game').children].filter(e=>e.id!=='modal'&&e.id!=='toast').forEach(e=>e.inert=true);$('modal').querySelectorAll('[data-close]').forEach(b=>b.onclick=close);$('modal').querySelector('button,select')?.focus();}
function head(t){return `<div class="sheet-head"><h2 id="sheet-title">${escape(t)}</h2><button data-close aria-label="닫기">×</button></div>`;}
function close(){$('modal').innerHTML='';[...$('game').children].forEach(e=>e.inert=false);if(returnFocus?.isConnected)returnFocus.focus();}
function inventory(present=false){open(head(present?'증거 제시':'조사 수첩')+(present?`<p class="current-claim">${escape(claims()[s.statement])}</p>`:'<p class="book-intro">직접 확인한 것만 기록한다.</p>')+(s.found.length?'<div class="evidence-list">'+s.found.map(id=>`<button data-evidence="${id}"><span class="evidence-icon">${id==='key'?'⚿':id==='clock'?'◷':'▤'}</span><span><b>${EVIDENCE[id].title}</b><small>${s.read.includes(id)?'읽은 기록':'내용 확인'}</small></span><span>›</span></button>`).join('')+'</div>':'<p>아직 기록이 없다. 대화 뒤에 현장을 조사해 보자.</p>'));document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>detail(b.dataset.evidence,present));}
function detail(id,present=false){const e=EVIDENCE[id];if(!s.read.includes(id)){s.read.push(id);save();}open(head(e.title)+`<p>${e.desc}</p><article class="paper">${e.body}</article><details><summary>다람의 메모 보기</summary><p>${e.note}</p></details><div class="actions">${button('detail-back','수첩 목록')}${present?button('submit','이 증거 제시','gold'):button('return','돌아가기','gold')}</div>`);$('detail-back').onclick=()=>inventory(present);if(present)$('submit').onclick=()=>submit(id);else $('return').onclick=close;}
function resetPrompt(){open(head('처음부터 시작')+'<p>이 1장의 진행 기록을 지우고 다시 시작합니다.</p>'+button('reset','새로 시작','gold wide'));$('reset').onclick=()=>{close();s=fresh();save();render();};}
$('start').onclick=()=>{$('title').hidden=true;s=fresh();save();render();};$('continue').hidden=!checkpoint;$('continue').onclick=()=>{$('title').hidden=true;s=checkpoint;render();};
$('notebook').onclick=()=>inventory(false);$('log').onclick=()=>open(head('대화 기록')+s.log.map(l=>`<div class="log-line"><b>${escape(l.name)}</b><p class="${l.thought?'thought':''}">${escape(l.text)}</p></div>`).join(''));
$('settings').onclick=()=>{open(head('설정')+'<label class="setting">글자 속도<select id="speed"><option value="45">천천히</option><option value="28">보통</option><option value="0">바로 표시</option></select></label><p>진행은 이 브라우저에 자동 저장됩니다.</p>'+button('reset-menu','처음부터','wide'));$('speed').value=s.speed;$('speed').onchange=e=>{s.speed=Number(e.target.value);save();if(!s.speed&&timer){stop();typed=full.length;$('text').textContent=full;}};$('reset-menu').onclick=resetPrompt;};
window.addEventListener('resize',placeSpots);
document.addEventListener('keydown',e=>{if($('modal').childElementCount){if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const a=[...$('modal').querySelectorAll('button,select,summary')],first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if((e.key==='Enter'||e.key===' ')&&s.mode==='dialogue'&&[document.body,$('advance')].includes(document.activeElement)){e.preventDefault();advance();}});
actor('daram',0);count();window.chapterStartReady?.();
})();
