/* Original attachments are copied byte-for-byte. CSS windows reveal original frame/paper pixels. */
window.DaramReference=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pos=(x,y,w,h)=>`left:${x/588*100}%;top:${(y-117)/1046*100}%;width:${w/588*100}%;height:${h/1046*100}%`;
 const crop=(file,x,y,w,h)=>`background-image:url(assets/reference/${file}.jpg);background-size:${588/w*100}% ${1280/h*100}%;background-position:${x/(588-w)*100}% ${y/(1280-h)*100}%;`;
 const box=(x,y,w,h,html,cls='ref-paper',attrs='')=>`<div class="ref-area ${cls}" style="${pos(x,y,w,h)}" ${attrs}>${html}</div>`;
 const hot=(x,y,w,h,label,attrs)=>`<button class="ref-area ref-hot" style="${pos(x,y,w,h)}" aria-label="${esc(label)}" ${attrs}><span>${esc(label)}</span></button>`;
 const plane=(name,html,title)=>`<div class="ref-plane ref-${name}" style="--ref:url(assets/reference/${name}.jpg)"><h2 id="sheet-title" class="visually-hidden">${title}</h2>${html}</div>`;
 const paper=()=>crop('case',395,355,10,10);
 const thumb=id=>DaramEvidenceArt.thumb(id,EVIDENCE[id].title);
 function board(s,core){const ids=['receipt','tray','key','cabinet','roster','report'],places=[[60,432,136,170],[246,435,89,125],[368,438,94,141],[220,596,139,148],[58,639,142,102],[369,631,92,108]];let body=hot(18,128,41,40,'닫기','data-close');const tabs=[['case','사건'],['people','인물'],['evidence','단서'],['timeline','사건 순서'],['testimony','증언']];tabs.forEach(([id,label],i)=>body+=hot(35+i*106,245,101,43,label,`data-tab="${id}"`));body+=box(54,300,364,88,'<small>Case. 01 · 눈길 거처</small><h3>사라진 봉투</h3><p>받았다는 서명은 어디까지 확인한 걸까?</p>');
 places.forEach(([x,y,w,h],i)=>{const id=ids[i],owned=s.found.includes(id);body+=box(x,y,w,h,owned?`<button data-board-evidence="${id}" class="ref-content-button">${thumb(id)}<b>${EVIDENCE[id].title}</b></button>`:'<span class="ref-unknown">?</span><small>아직 찾지 못한 단서</small>','ref-paper ref-board-card');});
 body+=box(32,810,246,120,'주민들에게 줄 지원금 봉투가 사라졌다. 까로의 배달 기록과 뭉치의 이야기를 직접 확인해 보자.');const tasks=[['접수증 검사',!!core.state.exam.receipt],['직접 본 일 질문',s.asked.includes('witness')],['첫 증언 확인',!!core.state.broken['round:0']],['예비 열쇠 검사',!!core.state.exam.key],['명단·보고서 연결',s.found.includes('cx_reception_2')]];
 body+=box(315,785,240,150,`<b>현재 추리 상황 ${tasks.filter(x=>x[1]).length}/5</b>${tasks.map(([t,v])=>`<p>${v?'☑':'☐'} ${t}</p>`).join('')}`,'ref-ink');body+=hot(310,947,249,83,'단서 이어 보기','id="board-hypothesis"');return plane('case',body,'사건 수첩');}
 function controller({open,checkpoint,slots,restore}){
  function clues(filter='all',selected=null,page=0){const all=checkpoint()?.found||[],isPaper=id=>['receipt','roster','report','envelope'].includes(id)||id.startsWith('cx_'),ids=all.filter(id=>EVIDENCE[id]&&(filter==='all'||(filter==='paper'?isPaper(id):!isPaper(id))));selected=ids.includes(selected)?selected:ids[0];let h=hot(20,132,73,59,'닫기','data-close');[['all','전체'],['paper','문서'],['object','물건']].forEach(([id,label],i)=>h+=box(94+i*95,336,80,37,`<button data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`));h+=box(389,337,79,35,`<button data-next-clues>다음 ›</button>`);h+=box(481,314,89,50,`모은 단서<br><b>${all.length}개</b>`);
   for(let i=0;i<6;i++){const id=ids[page*6+i],x=113+i%3*150,y=391+Math.floor(i/3)*157;h+=box(x,y,125,138,id?`<button data-clue="${id}" aria-pressed="${selected===id}" class="ref-content-button">${thumb(id)}<b>${EVIDENCE[id].title}</b></button>`:'<span class="ref-unknown">?</span><small>찾은 단서를 붙이는 자리</small>','ref-paper ref-clue-cell');}
   h+=box(61,766,162,156,selected?thumb(selected):'<span class="ref-unknown">?</span>','ref-ink ref-selected-picture');h+=box(252,738,290,184,selected?`<h3>${EVIDENCE[selected].title}</h3><p>${esc(EVIDENCE[selected].desc)}</p><small>발견 장소</small><p>${ROOMS.find(r=>r.spots.some(x=>x.id===selected))?.name||'대화와 단서 비교'}</p>`:'<h3>첫 단서를 기다리는 중</h3><p>현장에서 궁금한 곳을 눌러 보세요.</p>','ref-paper ref-detail-copy ref-scroll');h+=box(267,942,249,62,selected?esc(EVIDENCE[selected].memo):'작은 단서도 잊지 말고 적어 두자.');
   open(plane('clues',h,'단서 모음'));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>clues(b.dataset.filter));document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>clues(filter,b.dataset.clue,page));document.querySelector('[data-next-clues]').onclick=()=>clues(filter,selected,(page+1)%Math.max(1,Math.ceil(ids.length/6)));
  }
  function friends(pick='daram'){const ids=['daram','karo',...(checkpoint()?.round>1?['mungchi']:[])],p=PEOPLE[pick];let h=hot(17,135,135,42,'닫기','data-close');if(pick!=='daram')h+=box(33,339,265,178,portrait(pick),'ref-ink');h+=box(313,338,238,183,`<h3>${p.name}</h3><small>${p.role}</small><p>${p.fact}</p><p>“${p.memo}”</p>`);h+=box(27,555,525,27,'만난 친구의 사진을 눌러 보세요.','ref-ink');
   for(let i=0;i<6;i++){const id=ids[i],x=31+i%3*189,y=607+Math.floor(i/3)*246;h+=box(x,y,158,219,id?`<button data-friend="${id}" class="ref-content-button">${portrait(id)}<b>${PEOPLE[id].name}</b><small>${PEOPLE[id].role}</small></button>`:'<span class="ref-unknown">?</span><b>아직 만나지 못한 친구</b><small>이야기 속에서 만나게 될 거야.</small>','ref-paper ref-friend-cell');}open(plane('friends',h,'친구들'));document.querySelectorAll('[data-friend]').forEach(b=>b.onclick=()=>friends(b.dataset.friend));
  }
  function portrait(id){return `<div class="ref-portrait" role="img" aria-label="${PEOPLE[id].name}" style="background-image:url(${DaramArt.source(id)})"></div>`;}
  function saves(page=0){const entries=[{label:'자동 저장',state:checkpoint()},...slots().map((v,i)=>({label:'저장 파일 '+(i+1),state:v?.state,at:v?.at}))];let h=hot(20,147,139,50,'닫기','data-close');for(let i=0;i<3;i++){const n=page*3+i,v=entries[n],y=471+i*173,r=ROOMS[v?.state?.room||0]||ROOMS[0];h+=box(26,y-4,157,25,v?.label||'빈 기록');h+=box(33,y+24,145,113,v?.state?`<img src="assets/${r.asset}.png" alt="${r.name}">`:'<span class="ref-unknown">?</span>','ref-ink ref-save-picture');h+=box(198,y+2,220,148,v?.state?`<small>첫 번째 사건</small><h3>사라진 봉투</h3><p>${v.state.finished?'해결한 사건':'조사 중'} · 단서 ${v.state.found.length}개</p><small>${v.at?new Date(v.at).toLocaleDateString('ko-KR'):'자동 기록'}<br>${r.name}</small>`:'<h3>비어 있는 기록</h3><p>게임 설정에서 진행을 저장할 수 있어요.</p>');h+=box(433,y+80,128,66,v?.state?'작은 단서도 잊지 말자.':'새 이야기를 기다리는 중.');h+=hot(427,y+9,128,50,'이어하기',`data-resume="${n}" ${v?.state?'':'disabled'}`);if(!v?.state)h+=box(438,y+18,107,30,'빈 기록');}h+=hot(26,998,295,64,'다른 저장 기록 보기','data-next-saves');open(plane('saves',h,'계속하기'));document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>restore(entries[+b.dataset.resume].state));document.querySelector('[data-next-saves]').onclick=()=>saves(1-page);}
  return {clues,friends,saves};
 }
 return {pos,crop,paper,board,controller,plane,box,hot};
})();
