/* Real saved records, dressed as a desk full of photographs and paper notes. */
window.createScrapbook=({open,esc,checkpoint,slots,restore})=>{
 const paw='<svg class="paw" viewBox="0 0 32 32" aria-hidden="true"><ellipse cx="6" cy="11" rx="4" ry="5"/><ellipse cx="14" cy="6" rx="4" ry="5"/><ellipse cx="23" cy="8" rx="4" ry="5"/><ellipse cx="28" cy="16" rx="3" ry="4"/><path d="M9 21Q14 10 21 18L27 26Q27 32 18 28Q7 31 6 26Z"/></svg>';
 const thumb=id=>DaramEvidenceArt.thumb(id,EVIDENCE[id].title);
 const portrait=id=>`<div class="scrap-portrait ${id}" role="img" aria-label="${esc(PEOPLE[id].name)}" style="background-image:url(${DaramArt.source(id)})"></div>`;
 function shell(title,tag,body){open(`<div class="scrapbook"><div class="scrap-hero"><button data-close class="scrap-back">‹ 돌아가기</button><aside class="scrap-note hero-note">작은 단서도<br>언젠가,<br>큰 진실로 이어져.${paw}</aside><h2 id="sheet-title">${paw}${title}</h2><p class="scrap-ribbon">${tag}</p><small>DARAM’S CASE FILES</small></div>${body}<footer class="scrap-footer"><span>조금 느려도 괜찮아.<br>다람의 수첩은 늘 열려 있어.</span>${paw}</footer></div>`);}
 function clues(filter='all',pick=null){const state=checkpoint(),all=(state?.found||[]).filter(id=>EVIDENCE[id]);const paper=id=>['receipt','envelope','roster','report'].includes(id)||id.startsWith('cx_');const ids=all.filter(id=>filter==='all'||(filter==='paper'?paper(id):!paper(id)));const selected=ids.includes(pick)?pick:ids[0];
 const tabs=[['all','전체'],['paper','문서'],['object','물건']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${id==='all'?paw:id==='paper'?'▤':'◇'} ${label}</button>`).join('');
 let body=`<section class="scrap-binding"><nav class="scrap-tabs" aria-label="단서 분류">${tabs}<span class="scrap-count">모은 단서<br><b>${all.length}개</b></span></nav><div class="scrap-grid">`;
 body+=ids.map(id=>`<button class="scrap-card" data-clue="${id}" aria-pressed="${id===selected}"><span class="scrap-image">${thumb(id)}${paw}</span><b>${esc(EVIDENCE[id].title)}</b></button>`).join('');
 if(!ids.length)body+=`<div class="scrap-empty scrap-note">${paw}<h3>첫 단서를 기다리는 중!</h3><p>${all.length?'이 분류에는 아직 단서가 없어요.':'궁금한 곳을 콕 눌러 봐.<br>찾은 단서는 여기 붙여 둘게!'}</p></div>`;
 body+='</div></section>';
 if(selected){const e=EVIDENCE[selected],r=ROOMS.find(r=>r.spots.some(x=>x.id===selected));body+=`<article class="scrap-detail"><figure class="scrap-photo">${thumb(selected)}<figcaption>다람이 찾았다! ${paw}</figcaption></figure><div><small class="scrap-label">${paper(selected)?'문서 기록':'발견한 물건'}</small><h3>${esc(e.title)}</h3><p>${esc(e.desc)}</p>${r?`<div class="scrap-location"><img src="assets/${r.asset}.png" alt=""><span>발견한 장소<br><b>${esc(r.name)}</b></span></div>`:''}</div><aside class="scrap-note detail-note"><b>다람의 작은 메모</b><p>${esc(e.memo)}</p>${paw}</aside></article>`;}
 shell('단서 모음','수집한 단서를 확인해요',body);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>clues(b.dataset.filter));document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>clues(filter,b.dataset.clue));
 }
 function friends(pick='daram'){const state=checkpoint(),ids=['daram','karo',...(state?.round>1?['mungchi']:[])];if(!ids.includes(pick))pick='daram';const p=PEOPLE[pick];
 shell('친구들','함께하는 소중한 친구들',`<article class="scrap-friend-feature"><div class="scrap-photo">${portrait(pick)}</div><div><h3>${esc(p.name)} ${paw}</h3><small>${esc(p.role)}</small><p>${esc(p.fact)}</p><aside class="scrap-note"><p>“${esc(p.memo)}”</p></aside></div></article><p class="scrap-caption">${paw} 수첩에 적어 둔 얼굴들</p><div class="scrap-friends">${ids.map(id=>`<button class="scrap-card" data-friend="${id}" aria-pressed="${id===pick}">${portrait(id)}<b>${esc(PEOPLE[id].name)} ${paw}</b><small>${esc(PEOPLE[id].role)}</small></button>`).join('')}${state?.round>1?'':'<div class="scrap-card scrap-locked"><strong>?</strong><b>아직 만나지 못한 친구</b><small>사건 속에서 만나게 될 거야.</small></div>'}</div><aside class="scrap-note father-note"><b>서진 · 다람의 아빠</b><p>내 편. 가끔 너무 내 편이라 내가 한 번 더 물어봐야 함.</p>${paw}</aside>`);
 document.querySelectorAll('[data-friend]').forEach(b=>b.onclick=()=>friends(b.dataset.friend));
 }
 function saves(){const auto=checkpoint(),manual=slots(),entries=[{state:auto,label:'자동 저장'},...manual.map((v,i)=>({state:v?.state,at:v?.at,label:'저장 파일 '+(i+1)}))];
 shell('계속하기','지난 이야기를 이어서',`<div class="scrap-saves">${entries.map((v,i)=>{if(!v.state)return `<article class="scrap-save empty-save"><span>＋</span><div><b>${v.label}</b><p>아직 비어 있는 수첩이에요.</p></div></article>`;const s=v.state,r=ROOMS[s.room||0]||ROOMS[0];return `<article class="scrap-save"><div class="save-picture"><img src="assets/${r.asset}.png" alt="${esc(r.name)}"><span>${v.label}</span></div><div class="save-copy"><small>첫 번째 사건</small><h3>사라진 봉투</h3><p>${s.finished?'사건 해결':s.round===2?'보관함과 보고서를 확인하는 중':'봉투가 전달된 일을 조사하는 중'}</p><div class="save-metadata">▤ 수집한 단서 ${s.found.length}개<br>⌖ ${esc(r.name)}${v.at?'<br>◷ '+new Date(v.at).toLocaleString('ko-KR'):''}</div><button data-resume="${i}">이어하기 ›</button></div><aside class="scrap-note">작은 의심도<br>잊지 말고 적어 두자.${paw}</aside></article>`;}).join('')}</div>`);
 document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>restore(entries[+b.dataset.resume].state));
 }
 return {clues,friends,saves};
};
