'use strict';
const DATA=window.ART_PRODUCTION;
const byId=new Map(DATA.assets.map(a=>[a.id,a]));
const names={daram:'다람',papa:'아빠',rei:'레이',karo:'까로',buri:'부리',wanggu:'왕구',doto:'도토'};
const expressions={neutral:'기본',happy:'활짝 웃음',think:'생각',smug:'의기양양',shock:'놀람',angry:'화남',sad:'시무룩',cry:'눈물 참기',smile:'미소',pout:'토라짐',nervous:'초조',embarrassed:'머쓱함',shy:'수줍음'};
const orders={daram:['neutral','happy','think','smug','shock','angry','sad','cry'],papa:['neutral','think','sad','smile'],rei:['neutral','smug','think','pout'],karo:['neutral','nervous','think','shock'],buri:['neutral','think','sad','shock'],wanggu:['neutral','think','embarrassed','shock'],doto:['neutral','think','shy','shock']};
const iconNames={investigate:'조사',move:'이동',evidence:'증거',notebook:'수첩',hint:'힌트',record:'기록',memo:'메모',present:'증거 제시',back:'돌아가기',menu:'메뉴','sound-on':'소리 켜짐','sound-off':'소리 꺼짐','detective-hat':'탐정 모자','flash-idea':'번뜩임','hidden-story':'숨은 이야기',badge:'배지',friends:'인물','mom-notebook':'엄마 수첩',letter:'편지','cloak-file':'검은 망토','world-map':'세계 지도',save:'저장',settings:'설정',lock:'잠금','trust-full':'신뢰','trust-empty':'빈 신뢰','star-full':'별','star-empty':'빈 별','lamp-life-on':'켜진 등불','lamp-life-off':'꺼진 등불',press:'추궁',objection:'이의 있음'};
const cached=new Map();let selectedExpression='neutral',faceRenderVersion=0;
function src(path){return '../'+path.replace(/^design\/retro\//,'');}
function loadImage(url){if(!cached.has(url))cached.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Image failed: '+url));im.src=url;}));return cached.get(url);}
async function draw(canvas,asset,size,crop=asset.crop){canvas.width=size;canvas.height=size;const im=await loadImage(src(asset.path));const ctx=canvas.getContext('2d');ctx.clearRect(0,0,size,size);ctx.imageSmoothingEnabled=false;ctx.drawImage(im,...crop,0,0,size,size);canvas.dataset.loaded='true';}
function faceAsset(char,expr){return byId.get(char+'-'+expr)||(char==='daram'?{id:'daram-'+expr,path:'design/retro/daram-face/'+expr+'.png',crop:[0,0,1254,1254]}:null);}
async function talk(){const char=document.querySelector('#character').value;const asset=faceAsset(char,selectedExpression);if(asset)await draw(document.querySelector('#talk-face'),asset,96);document.querySelector('#talk-name').textContent=names[char];}
async function faces(){const version=++faceRenderVersion;const char=document.querySelector('#character').value,size=Number(document.querySelector('#face-size').value);document.documentElement.style.setProperty('--face-size',size+'px');document.body.classList.toggle('large-faces',size===192);const grid=document.querySelector('#face-grid');grid.replaceChildren();const pending=[];
for(const expr of orders[char]){const asset=faceAsset(char,expr);if(!asset)continue;const button=document.createElement('button');button.type='button';button.className='face-card';button.dataset.expression=expr;button.setAttribute('aria-pressed',String(expr===selectedExpression));const canvas=document.createElement('canvas');canvas.className='surface';canvas.setAttribute('aria-label',names[char]+' '+expressions[expr]);const label=document.createElement('span');label.textContent=expressions[expr];button.append(canvas,label);button.onclick=()=>{selectedExpression=expr;for(const b of grid.children)b.setAttribute('aria-pressed',String(b===button));talk().catch(report);};grid.append(button);pending.push(draw(canvas,asset,size));}await Promise.all(pending);if(version===faceRenderVersion)await talk();}
async function icons(){const batch=document.querySelector('#icon-batch').value;const grid=document.querySelector('#icon-grid');grid.replaceChildren();const pending=[];for(const asset of DATA.assets.filter(a=>a.batch===batch).sort((a,b)=>Object.keys(iconNames).indexOf(a.id.replace(/^icon-/,''))-Object.keys(iconNames).indexOf(b.id.replace(/^icon-/,'')))){const id=asset.id.replace(/^icon-/,'');const card=document.createElement('figure');card.className='icon-card';const row=document.createElement('div');row.className='icon-sizes surface';for(const size of [22,32,36]){const canvas=document.createElement('canvas');canvas.setAttribute('aria-label',iconNames[id]+' '+size+'픽셀');canvas.style.width=size+'px';canvas.style.height=size+'px';row.append(canvas);pending.push(draw(canvas,asset,size));}const label=document.createElement('figcaption');label.textContent=iconNames[id];const link=document.createElement('a');link.href=src(asset.path);link.textContent=id+'.png';link.target='_blank';link.rel='noopener';card.append(row,label,link);grid.append(card);}await Promise.all(pending);}
async function hill(){const asset=byId.get('star-hill-evidence');if(!asset)return;const im=await loadImage(src(asset.path)),canvas=document.querySelector('#hill-canvas'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(im,...asset.crop,0,0,720,400);canvas.dataset.loaded='true';const daram=await loadImage('../daram-matched.png');const character=document.querySelector('#hill-character'),cc=character.getContext('2d');cc.imageSmoothingEnabled=false;cc.drawImage(daram,0,0,594,763,0,220-160*763/594,160,160*763/594);character.dataset.loaded='true';const hotspots=document.querySelector('#hill-hotspots');hotspots.replaceChildren();asset.evidence.forEach((e,i)=>{const b=document.createElement('button');b.className='hotspot';b.style.left=e.point[0]/360*100+'%';b.style.top=e.point[1]/200*100+'%';b.textContent=i+1;b.setAttribute('aria-label',e.name);b.onclick=()=>document.querySelector('#hill-clue').textContent=e.name+' · '+e.evidenceId;hotspots.append(b);});}
function title(){const wide=document.querySelector('#title-direction').value==='wide',asset=byId.get(wide?'title-bg-wide':'title-bg');if(!asset)return;document.querySelector('#title-stage').className='title-stage '+(wide?'wide':'portrait');document.querySelector('#title-image').src=src(asset.path);document.querySelector('#title-original').href=src(asset.path);}
function report(error){console.error(error);document.querySelector('#count').textContent='이미지 확인 필요';}
function setTab(tab){for(const b of document.querySelectorAll('nav button'))b.setAttribute('aria-selected',String(b.dataset.tab===tab));for(const id of ['faces','hill','title','icons','wood'])document.getElementById(id).hidden=id!==tab;history.replaceState(null,'','#'+tab);}
document.querySelector('#count').textContent=DATA.generatedImageCount+'장 제작';
for(const button of document.querySelectorAll('nav button'))button.onclick=()=>setTab(button.dataset.tab);
document.querySelector('#character').onchange=()=>{selectedExpression='neutral';faces().catch(report);};document.querySelector('#face-size').onchange=()=>faces().catch(report);
for(const select of document.querySelectorAll('.surface-select'))select.onchange=()=>{document.body.dataset.surface=select.value;for(const other of document.querySelectorAll('.surface-select'))other.value=select.value;};
document.querySelector('#icon-batch').onchange=()=>icons().catch(report);
document.querySelector('#hill-daram').onchange=e=>document.querySelector('#hill-character').hidden=!e.target.checked;
document.querySelector('#hill-points').onchange=e=>document.querySelector('#hill-hotspots').hidden=!e.target.checked;
document.querySelector('#title-direction').onchange=title;
document.querySelector('#title-ui').onchange=e=>document.querySelector('.title-overlay').hidden=!e.target.checked;
document.querySelector('#title-zones').onchange=e=>document.querySelector('.safe-zones').hidden=!e.target.checked;
for(const [batch,archive] of Object.entries(DATA.archives)){const a=document.createElement('a');a.href=batch+'-assets.zip';a.textContent=batch+' · ZIP ('+(archive.bytes/1048576).toFixed(1)+'MB)';document.querySelector('#downloads').append(a);}
setTab(['faces','hill','title','icons','wood'].includes(location.hash.slice(1))?location.hash.slice(1):'faces');
for(const [id,element] of [['wood-tile','wood-normal'],['wood-tile-dark','wood-dark']]){const a=byId.get(id);if(a)document.getElementById(element).style.backgroundImage='url("'+src(a.path)+'")';}
Promise.all([faces(),icons(),hill()]).catch(report);title();
