"""Reuse original game's six synthesized themes and SFX, with a mobile lifecycle adapter."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1]
src=(root.parent/'game.html').read_text()
start=src.index('var AC=null,MASTER,BGMG,SFXG,NOISE,MGAIN=2.4;')
end=src.index('var HB=null;',start)
original=src[start:end]
adapter=(root/'tools/audio-adapter.js').read_text()
(root/'audio.js').write_text('/* Generated by tools/extract_audio.py from original game.html. */\n(()=>{\nconst S={sound:false};\n'+original+'\n'+adapter+'\n})();\n')
(root/'audio-provenance.json').write_text(json.dumps({'source':'game.html','startLine':src[:start].count('\n')+1,'sha256':hashlib.sha256(original.encode()).hexdigest(),'themes':['calm','sneak','talk','battle','pursuit','win'],'adapter':'tools/audio-adapter.js'},indent=2)+'\n')
