(()=>{'use strict';const $=id=>document.getElementById(id),kit=window.DaramArtKit;let manifest,selected=null,costume=null,expression=0,scene='main';
const regions={forest:'숲속 마을',silver:'은빛 마을',mine:'광산 마을',city:'도시'};
function cast(){const query=$('search').value.trim().toLowerCase(),region=$('region').value,items=manifest.order.map(id=>manifest.characters[id]).filter(c=>(region==='all'||c.region===region)&&(!query||[c.name,c.species,c.kind,c.role,c.bio,c.design].join(' ').toLowerCase().includes(query)));$('cast-count').textContent=items.length;$('cast-grid').replaceChildren();items.forEach(c=>{const button=document.createElement('button');button.className='cast-card';button.setAttribute('aria-label',c.name+' 캐릭터 보기');const portrait=document.createElement('div');portrait.className='cast-portrait';kit.character(portrait,c.id,0);const name=document.createElement('h3');name.textContent=c.name;const meta=document.createElement('p');meta.textContent=c.species+' · '+regions[c.region];button.append(portrait,name,meta);button.onclick=()=>showCharacter(c.id);$('cast-grid').append(button);});$('no-results').hidden=items.length>0;}
function paintCharacter(){const id=costume||selected,c=manifest.characters[id];kit.character($('character-large'),id,expression);$('character-download').href=kit.url(c.src);$('character-download').download=c.src.split('/').pop();$('expression-buttons').replaceChildren();['기본','생각·의심','감정'].forEach((label,i)=>{const button=document.createElement('button');button.textContent=label;button.setAttribute('aria-pressed',i===expression);button.onclick=()=>{expression=i;paintCharacter();};$('expression-buttons').append(button);});$('costumes').replaceChildren();if(selected==='nero'&&manifest.characters.luka&&manifest.characters.shadow){$('costumes').hidden=false;[['nero','네로'],['luka','루카 변장'],['shadow','검은 망토']].forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',id===(costume||selected));b.onclick=()=>{costume=id;paintCharacter();};$('costumes').append(b);});}else $('costumes').hidden=true;}
function showCharacter(id){selected=id;costume=null;expression=0;const c=manifest.characters[id];$('character-name').textContent=c.name;$('character-kind').textContent=c.species+' · '+(c.role||c.kind);$('character-bio').textContent=c.bio;$('character-design').textContent=c.design;paintCharacter();$('character-dialog').showModal();$('dialog-close').focus();}
function showScene(id){scene=id;const c=manifest.backgrounds[id];kit.background($('scene-preview'),id);$('scene-name').textContent=c.name;$('scene-download').href=kit.url(c.src);$('scene-download').download=c.src.split('/').pop();document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scene===id));}
$('dialog-close').onclick=()=>$('character-dialog').close();$('character-dialog').onclick=e=>{if(e.target!==$('character-dialog'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();};$('search').oninput=cast;$('region').onchange=cast;
$('toggle-actor').onclick=()=>{const hidden=!$('scene-actor').hidden;$('scene-actor').hidden=hidden;$('toggle-actor').setAttribute('aria-pressed',!hidden);};
kit.ready.then(m=>{manifest=m;kit.background($('hero-bg'),'main');kit.character($('hero-daram'),'daram',0);kit.character($('scene-actor'),'daram',0);cast();m.backgroundOrder.forEach(id=>{const c=m.backgrounds[id],b=document.createElement('button');b.className='scene-thumb';b.dataset.scene=id;b.setAttribute('aria-label',c.name+' 배경 보기');const art=document.createElement('div');art.className='thumb-art';kit.background(art,id);const title=document.createElement('p');title.textContent=c.name;b.append(art,title);b.onclick=()=>showScene(id);$('scene-thumbs').append(b);});showScene('main');}).catch(error=>{console.error(error);$('cast-grid').textContent='그림 목록을 불러오지 못했습니다. 새로고침해 주세요.';});
})();
