# Focus on an actual inhabitant; allow native pan in every cropped room.
rep('var FSX={};', 'var FSX={},FSGame=null;')
rep('    var key=G.ci+":"+G.loc,v=FSX[key];\n    fx.scrollLeft=v!=null?v:(fx.scrollWidth-fx.clientWidth)/2;', '''    if(FSGame!==G){FSGame=G;FSX={}}
    var key=G.ci+":"+G.loc,v=FSX[key],initial=(fx.scrollWidth-fx.clientWidth)/2;
    if(v==null&&CASES[G.ci].id==='inn'){
      var actor=sc.querySelector('image.wn9[data-k]');
      if(actor){var ar=actor.getBoundingClientRect(),fr=fx.getBoundingClientRect();initial=fx.scrollLeft+ar.left+ar.width/2-fr.left-fx.clientWidth/2}
    }
    fx.scrollLeft=v!=null?v:Math.max(0,Math.min(fx.scrollWidth-fx.clientWidth,initial));''')
rep(" var ROOT='art/ch1/locations/',pan=0;"," var ROOT='art/ch1/locations/',panByRoom={},panGame=null;")
rep(" function camera(k){var w=innerWidth,h=innerHeight,s,x,y,vw,vh;\n  if(k==='dining'){vh=Math.min(768,Math.max(520,1125*h/w));vw=vh*w/h;x=pan*Math.max(0,2048-vw);y=Math.max(0,Math.min(768-vh,400-vh/2));s=h/vh}\n  else{s=Math.max(w/1774,h/887);vw=w/s;vh=h/s;x=(1774-vw)/2;y=(887-vh)/2}\n  return {x:x,y:y,w:vw,h:vh,scale:s,width:w,height:h,pan:pan};\n }\n"," function camera(k){var w=innerWidth,h=innerHeight,s,x,y,vw,vh,wide=k==='dining'?2048:1774;\n  if(panGame!==G){panGame=G;panByRoom={}}\n  if(k==='dining'){vh=Math.min(768,Math.max(520,1125*h/w));vw=vh*w/h;y=Math.max(0,Math.min(768-vh,400-vh/2));s=h/vh}\n  else{s=Math.max(w/1774,h/887);vw=w/s;vh=h/s;y=(887-vh)/2}\n  var range=Math.max(0,wide-vw),focus=k==='dining'?855.5:k==='kitchen'?999.5:wide/2;\n  if(panByRoom[k]==null)panByRoom[k]=range?Math.max(0,Math.min(1,(focus-vw/2)/range)):0;\n  var p=panByRoom[k];x=p*range;\n  return {x:x,y:y,w:vw,h:vh,scale:s,width:w,height:h,pan:p};\n }\n")
rep("  ['fsal','fsar'].forEach(function(id,j){var b=document.getElementById(id);if(!b)return;b.style.setProperty('display',k==='dining'?'block':'none','important');b.disabled=k==='dining'&&(j?pan>=1:pan<=0);b.onclick=function(e){e.preventDefault();e.stopPropagation();pan=j?1:0;update()}});\n  if(!sc.__worldDrag){sc.__worldDrag=true;var drag=null;sc.addEventListener('pointerdown',function(e){if(k!=='dining'||e.target.closest('button'))return;drag={x:e.clientX,p:pan};sc.setPointerCapture(e.pointerId)});sc.addEventListener('pointermove',function(e){if(!drag)return;var range=2048-camera('dining').w;pan=Math.max(0,Math.min(1,drag.p-(e.clientX-drag.x)/c.scale/range));update()});sc.addEventListener('pointerup',function(){drag=null});sc.addEventListener('pointercancel',function(){drag=null})}","  ['fsal','fsar'].forEach(function(id,j){var b=document.getElementById(id);if(!b)return;var wide=k==='dining'?2048:1774,range=Math.max(0,wide-c.w),canPan=range>1;\n   b.style.setProperty('display',canPan?'block':'none','important');b.disabled=!canPan||(j?c.pan>=.999:c.pan<=.001);\n   var who=k==='dining'?[[855.5,'세련'],[1881,'할머니']]:k==='kitchen'?[[999.5,'나비'],[1505,'부리']]:[];\n   var out=who.filter(function(p){return j?p[0]>c.x+c.w:p[0]<c.x});if(j)out.sort(function(a,b){return a[0]-b[0]});else out.sort(function(a,b){return b[0]-a[0]});\n   if(out.length)b.dataset.person=out[0][1];else delete b.dataset.person;\n   b.setAttribute('aria-label',(j?'오른쪽':'왼쪽')+' 둘러보기'+(out.length?' · '+out[0][1]:''));\n   b.onclick=function(e){e.preventDefault();e.stopPropagation();if(DL||window.__dlFreeze)return;var now=camera(k);panByRoom[k]=Math.max(0,Math.min(1,now.pan+(j?1:-1)*Math.max(.15,now.w*.75/Math.max(1,range))));update()};\n  });\n  if(!sc.__worldDrag){sc.__worldDrag=true;var drag=null;\n   sc.addEventListener('pointerdown',function(e){if(DL||window.__dlFreeze||e.target.closest('button'))return;var now=camera(k),range=(k==='dining'?2048:1774)-now.w;if(range<=1)return;drag={x:e.clientX,p:now.pan,c:now,range:range};sc.setPointerCapture(e.pointerId)});\n   sc.addEventListener('pointermove',function(e){if(!drag)return;panByRoom[k]=Math.max(0,Math.min(1,drag.p-(e.clientX-drag.x)/drag.c.scale/drag.range));update()});\n   sc.addEventListener('pointerup',function(){drag=null});sc.addEventListener('pointercancel',function(){drag=null});\n  }")
